InventoryFrontEnd/Controllers/DashboardController.cs
using InventoryFrontEnd.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace InventoryFrontEnd.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index(string Campus_name)
        {
            Modelall mymodel = new Modelall();
            var inventoryController = new InventoryController();
            var result = inventoryController.Allrooms(Campus_name);
            var itemcount = inventoryController.Allitems(Campus_name);
            ViewBag.Campus_name = Campus_name;
            mymodel.Room_list = result;
            mymodel.Allitems = itemcount;
            ViewBag.firstName = Session["FirstName"];
            ViewBag.LastName = Session["LastName"];
            ViewBag.campusName = Session["campusName"];
            if (User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("", "login");
            }
            else
            {
                return View("~/Views/Dashboard/Index.cshtml", mymodel);
            }
        }

    
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("", "login");
        }


    }
}

InventoryFrontEnd/Controllers/InventoryController.cs
using InventoryFrontEnd.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace InventoryFrontEnd.Controllers
{
    public class InventoryController : Controller
    {

        //SHOW ALL Campus
        public ActionResult Campus()
        {
            Modelall mymodel = new Modelall();
            mymodel.Allcampus = campuses();
            if (User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("", "login");
            }
            else
            {
                return View("~/Views/Inventory/Campus.cshtml", mymodel);
            }
           

        }

        public IEnumerable<Campuses> campuses()
        {

            IEnumerable<Campuses> ec = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri(ConfigurationManager.AppSettings["API_Path"] + "API/Inventory/");

            var consumedata = hc.GetAsync("Campuses");
            consumedata.Wait();


            var dataread = consumedata.Result;
            if (dataread.IsSuccessStatusCode)
            {
                var results = dataread.Content.ReadAsAsync<IList<Campuses>>();
                results.Wait();
                ec = results.Result;
            }
            else if (dataread.StatusCode == HttpStatusCode.NotFound)
            {
                ec = Enumerable.Empty<Campuses>();
                ViewBag.Message = "No Locality Found.";
            }
            else
            {
                ec = Enumerable.Empty<Campuses>();
                ViewBag.Message = "Unable to display locality, please email to it@golden-success.com for help.";
            }
            return ec;
        }

        // ADD CAMPUS
        [HttpPost]
        [Route("insert/feedback/view2")]
        public ActionResult AddCampuscontroll(string add_campusnamevalue)
        {


            try
            {
                string msg;
                try
                {
                    WebRequest req;
                    WebResponse res;
                    string postData = "Campus_name=" + add_campusnamevalue;
                    req = WebRequest.Create(ConfigurationManager.AppSettings["API_Path"] + "API/Inventory/Add/Campus?" + postData);
                    Byte[] data = Encoding.UTF8.GetBytes(postData);
                    req.Method = "POST";
                    req.ContentType = "application/x-www-form-urlencoded; charset=UTF-8";
                    req.ContentLength = data.Length;

                    Stream stream = req.GetRequestStream();
                    stream.Write(data, 0, data.Length);
                    stream.Close();

                    using (res = req.GetResponse())
                    using (var reader = new StreamReader(res.GetResponseStream()))
                    {
                        msg = reader.ReadToEnd();

                        // Redirect back to the referring page
                        return Redirect(Request.UrlReferrer.ToString());
                    }
                }
                catch (WebException ex)
                {
                    HttpWebResponse res = (HttpWebResponse)ex.Response;
                    Stream receiveStream = res.GetResponseStream();
                    using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                    {
                        return Content("Catch: " + readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                    }
                }
            }
            catch (WebException ex)
            {
                HttpWebResponse res = (HttpWebResponse)ex.Response;
                Stream receiveStream = res.GetResponseStream();
                using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                {
                    return Content(readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                }
            }

        }

        //UPDATE CAMPUS
        [HttpPost]
        public ActionResult updatecampus(string update_Campus_id, string update_campus_name)
        {


            try
            {
                string msg;
                try
                {
                    WebRequest req;
                    WebResponse res;
                    string postData = "Campus_id=" + update_Campus_id + "&Campus_name=" + update_campus_name;
                    req = WebRequest.Create(ConfigurationManager.AppSettings["API_Path"] + "API/Inventory/Modify/Campus?" + postData);
                    Byte[] data = Encoding.UTF8.GetBytes(postData);
                    req.Method = "POST";
                    req.ContentType = "application/x-www-form-urlencoded; charset=UTF-8";
                    req.ContentLength = data.Length;

                    Stream stream = req.GetRequestStream();
                    stream.Write(data, 0, data.Length);
                    stream.Close();

                    using (res = req.GetResponse())
                    using (var reader = new StreamReader(res.GetResponseStream()))
                    {
                        msg = reader.ReadToEnd();

                        // Redirect back to the referring page
                        return Redirect(Request.UrlReferrer.ToString());
                    }
                }
                catch (WebException ex)
                {
                    HttpWebResponse res = (HttpWebResponse)ex.Response;
                    Stream receiveStream = res.GetResponseStream();
                    using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                    {
                        return Content("Catch: " + readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                    }
                }
            }
            catch (WebException ex)
            {
                HttpWebResponse res = (HttpWebResponse)ex.Response;
                Stream receiveStream = res.GetResponseStream();
                using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                {
                    return Content(readStream.ReadToEnd(), "text/plain", Encoding.UTF8);
                }
            }

        }

        //SHOW ALL ITEMS
        public ActionResult Item_list(string Campus_name)
        {
            Modelall mymodel = new Modelall();
            mymodel.Item_list = Allitems(Campus_name);
            mymodel.Allbrand = Brands(Campus_name);
            mymodel.Room_list = Allrooms(Campus_name);

            ViewBag.Campus_name = Campus_name;
            if (User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("", "login");
            }
            else
            {
                return View("~/Views/Inventory/item_list.cshtml", mymodel);
            }

        }
        public IEnumerable<Items> Allitems(string Campus_name)
        {

            IEnumerable<Items> ec = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri(ConfigurationManager.AppSettings["API_Path"] + "API/Inventory/Item/");

            var consumedata = hc.GetAsync("All?Campus_name=" + Campus_name);
            consumedata.Wait();


            var dataread = consumedata.Result;
            if (dataread.IsSuccessStatusCode)
            {
                var results = dataread.Content.ReadAsAsync<IList<Items>>();
                results.Wait();
                ec = results.Result;
            }
            else if (dataread.StatusCode == HttpStatusCode.NotFound)
            {
                ec = Enumerable.Empty<Items>();
                ViewBag.Message = "No Locality Found.";
            }
            else
            {
                ec = Enumerable.Empty<Items>();
                ViewBag.Message = "Unable to display locality, please email to it@golden-success.com for help.";
            }
            return ec;
        }

        //ADD ITEMS 

        [HttpPost]
        public ActionResult createitems(string add_item_name, string add_model, string add_brand, string add_serial_number, string add_item_type, string add_item_status, string add_item_department, string add_date, string add_room, string add_campus)
        {
            try
            {
                string msg;
                try
                {
                    WebRequest req;
                    WebResponse res;
                    string postData = "Item_name=" + add_item_name + "&Model=" + add_model + "&Brand=" + add_brand + "&Serial_number=" + add_serial_number + "&Item_type=" + add_item_type + "&Item_status=" + add_item_status + "&Department=" + add_item_department + "&Date_now=" + add_date + "&Room_name=" + add_room + "&Campus_name=" + add_campus;
                    req = WebRequest.Create(ConfigurationManager.AppSettings["API_Path"] + "API/Inventory/Add/Newitems?" + postData);
                    Byte[] data = Encoding.UTF8.GetBytes(postData);
                    req.Method = "POST";
                    req.ContentType = "application/x-www-form-urlencoded; charset=UTF-8";
                    req.ContentLength = data.Length;

                    Stream stream = req.GetRequestStream();
                    stream.Write(data, 0, data.Length);
                    stream.Close();

                    using (res = req.GetResponse())
                    using (var reader = new StreamReader(res.GetResponseStream()))
                    {
                        msg = reader.ReadToEnd();

                        // Redirect back to the referring page
                        return Redirect(Request.UrlReferrer.ToString());
                    }
                }
                catch (WebException ex)
                {
                    HttpWebResponse res = (HttpWebResponse)ex.Response;

InventoryFrontEnd/Controllers/MaterialsController.cs
using InventoryFrontEnd.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace InventoryFrontEnd.Controllers
{
    public class MaterialsController : Controller
    {
        // GET: Materials
        public ActionResult materialslist(string Campus_name)
        {
            Modelall mymodel = new Modelall();
            mymodel.AllMaterials = AllMaterials(Campus_name);
            ViewBag.campus_name = Campus_name;
            if (User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("", "login");
            }
            else
            {
                return View("~/Views/Materials/materialslist.cshtml", mymodel);
            }
        }


        public IEnumerable<Materials_list> AllMaterials(string Campus_name)
        {
            try
            {
                IEnumerable<Materials_list> ec = null;
                HttpClient hc = new HttpClient();
                hc.BaseAddress = new Uri(ConfigurationManager.AppSettings["API_Path"] + "API/Materials/Supply/");

                var consumedata = hc.GetAsync("List?Campus_name=" + Campus_name);
                consumedata.Wait();

                var dataread = consumedata.Result;
                if (dataread.IsSuccessStatusCode)
                {
                    var results = dataread.Content.ReadAsAsync<IList<Materials_list>>();
                    results.Wait();
                    ec = results.Result;
                }
                else if (dataread.StatusCode == HttpStatusCode.NotFound)
                {
                    ec = Enumerable.Empty<Materials_list>();
                    ViewBag.Message = "No Rooms Found for the selected campus.";
                }
                else
                {
                    ec = Enumerable.Empty<Materials_list>();
                    ViewBag.Message = "Unable to retrieve room data. Please contact support for assistance.";
                }
                return ec;
            }
            catch (Exception ex)
            {

                ViewBag.Message = "An error occurred: " + ex.Message;
                return Enumerable.Empty<Materials_list>();
            }
        }
    }
}

InventoryFrontEnd/Views/Materials/materialslist.cshtml
@using InventoryFrontEnd.Models;
@model Modelall
@{
    ViewBag.Title = "ALL ROOMS";

}
<head>

    <script src="~/JS Scripts/Materials functions.js"></script>

</head>
<body>
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-md-2 mb-4 d-flex flex-column">
                <div class="card shadow rounded-4 sidebar">
                    <div class="card-body">
                        <h4 class="text-primary">@ViewBag.campus_name</h4>
                        <h6 class="mb-3">Navigation</h6>
                        <a href="@Url.Action("Index", "Dashboard", new { campus_name = ViewBag.campus_name })"
                           class="btn btn-outline-secondary mb-2 w-100 text-start">
                            <i class="bi bi-tags me-1"></i>Home
                        </a>
                        <a href="@Url.Action("Campus", "Inventory", new { campus_name = ViewBag.campus_name })"
                           class="btn btn-outline-secondary mb-2 w-100 text-start">
                            <i class="bi bi-bank2"></i>Campus List
                        </a>
                        <a href="@Url.Action("brandlist", "Inventory", new { campus_name = ViewBag.campus_name })"
                           class="btn btn-outline-secondary mb-2 w-100 text-start">
                            <i class="bi bi-tags me-1"></i> Brand List
                        </a>
                        <a href="@Url.Action("Item_list", "Inventory", new { campus_name = ViewBag.campus_name })"
                           class="btn btn-outline-secondary mb-2 w-100 text-start">
                            <i class="bi bi-box-fill"></i> Item List
                        </a>
                        <a href="@Url.Action("rooms", "Inventory", new { campus_name = ViewBag.campus_name })"
                           class="btn btn-outline-secondary mb-2 w-100 text-start">
                            <i class="bi bi-tags me-1"></i> Room List
                        </a>
                        <a href="@Url.Action("materialslist", "Materials", new { campus_name = ViewBag.campus_name })"
                           class="btn btn-outline-secondary mb-3 w-100 text-start">
                            <i class="bi bi-tags me-1"></i>Materials List
                        </a>
                        <a href="@Url.Action("itemlogs", "Inventory", new { campus_name = ViewBag.campus_name })"
                           class="btn btn-outline-secondary mb-3 w-100 text-start">
                            <i class="bi bi-clipboard2-data"></i> Item Logs
                        </a>
                        <a href="@Url.Action("logout", "dashboard")"
                           class="btn btn-outline-secondary mb-3 w-100 text-start">
                            <i class="bi bi-box-arrow-right me-1"></i> Log Out
                        </a>
                    </div>
                </div>
            </div>


            <!-- Main Content -->
            <div class="col-md-10">
                <div class="card shadow rounded-4">
                    <div class="card-body">
                        <!-- Header -->
                        <div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-3">
                            <div>
                                <h2 class="mb-1 text-primary">@ViewBag.campus_name</h2>
                                <h4 class="mb-0">Materials List</h4>
                            </div>
                        </div>

                        <!-- Table -->
                        <div class="table-responsive">
                            <table class="table table-hover table-striped table-bordered align-middle text-center">
                                <thead class="table-dark">
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Quantity</th>
                                        <th>Date Received</th>
                                        <th>Unit</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.AllMaterials.OrderBy(x => x.Material_name))
                                    {
                                        <tr class="clickable-row" role="button"
                                            data-bs-toggle="modal"
                                            data-bs-target="#detailsModal"
                                            data-id="@item.Material_ID"
                                            data-name="@item.Material_name"
                                            data-quantity="@item.Quantity"
                                            data-receiveddate="@item.Received_date"
                                            data-unit="@item.Unit"
                                            data-datepurchased="@item.Date_Purchased"
                                            data-requestby="@item.Request_by"
                                            data-approveby="@item.Approve_by"
                                            data-status="@item.Status"
                                            data-supplier="@item.Supplier"
                                            data-receivedby="@item.Received_By"
                                            data-campusname="@item.Campus_name">
                                            <td>@item.Material_ID</td>
                                            <td>@item.Material_name</td>
                                            <td>@item.Quantity</td>
                                            <td>@item.Received_date</td>
                                            <td>@item.Unit</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                            <!-- Pagination -->
                            <div class="d-flex justify-content-center mt-3">
                                <nav>
                                    <ul class="pagination" id="pagination"></ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="detailsModal" tabindex="-1" aria-labelledby="detailsModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content rounded-4 shadow-lg border-0">

                <!-- Modal Header -->
                <div class="modal-header text-white rounded-bottom-4" style="background: linear-gradient(135deg, #007bff, #0056b3);">
                    <h1>Materials Details</h1>
                </div>

                <!-- Modal Body -->
                <div class="modal-body py-4 px-4 bg-light">
                    <div class="row g-4">
                        <div class="col-sm-6">
                            <h6 class="fw-bold text-muted">Date Purchased</h6>
                            <p id="modalDatePurchased" class="mb-0 text-dark"></p>
                        </div>
                        <div class="col-sm-6">
                            <h6 class="fw-bold text-muted">Request By</h6>
                            <p id="modalRequestBy" class="mb-0 text-dark"></p>
                        </div>
                        <div class="col-sm-6">
                            <h6 class="fw-bold text-muted">Approve By</h6>
                            <p id="modalApproveBy" class="mb-0 text-dark"></p>
                        </div>
                        <div class="col-sm-6">
                            <h6 class="fw-bold text-muted">Status</h6>
                            <p id="modalStatus" class="mb-0 text-dark"></p>
                        </div>
                        <div class="col-sm-6">
                            <h6 class="fw-bold text-muted">Supplier</h6>
                            <p id="modalSupplier" class="mb-0 text-dark"></p>
                        </div>
                        <div class="col-sm-6">
                            <h6 class="fw-bold text-muted">Received By</h6>
                            <p id="modalReceivedBy" class="mb-0 text-dark"></p>
                        </div>
                        <div class="col-sm-6">
                            <h6 class="fw-bold text-muted">Campus Name</h6>
                            <p id="modalCampusName" class="mb-0 text-dark"></p>
                        </div>
                    </div>
                </div>

                <!-- Modal Footer -->
                <div class="modal-footer text-white rounded-bottom-4" style="background: linear-gradient(135deg, #007bff, #0056b3);">
                    <button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">
                        <i class="bi bi-x-circle"></i> Close
                    </button>
                </div>

            </div>
        </div>
    </div>


    <!-- ADD Modal -->

    <div class="modal fade add-item-modal" id="createroombtn" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-static">
            <div class="modal-content">
                <div class="modal-header bg-primary text-white">
                    <h2 class="modal-title" id="exampleModalLabel">ADD NEW ROOM</h2>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="row mb-3">
                            <div class="col-12 col-md-6">
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="add_room_name" name="add_room_name" placeholder=" " autocomplete="off" required />
                                    <label for="add_room_name" class="form-label">Room Name</label>
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-floating mb-3">
                                    <select class="form-select" id="add_floor_level" name="add_floor_level" required>
                                        <option value="" disabled selected hidden>Choose FLOOR LEVEL</option>
                                        <option value="1ST FLOOR">1ST FLOOR</option>
                                        <option value="2ND FLOOR">2ND FLOOR</option>
                                        <option value="3RD FLOOR">3RD FLOOR</option>
                                        <option value="4TH FLOOR">4TH FLOOR</option>
                                        <option value="5TH FLOOR">5TH FLOOR</option>
                                        <option value="ROOFTOP">ROOFTOP</option>
                                    </select>
                                    <label for="add_floor_level" class="form-label">Floor Level</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="add_room_description" name="add_room_description" placeholder=" " autocomplete="off" required />
                                    <label for="add_room_description" class="form-label">Room Description</label>
                                </div>
                            </div>
                        </div>
                        <div class="visually-hidden">
                            <input type="text" class="form-control" id="add_campus_name" value="@ViewBag.campus_name" name="add_campus_name" autocomplete="off" readonly />
                        </div>
                    </form>
                </div>
                <div class="modal-footer fixed-bottom text-center">
                    <button class="btn btn-success" id="addroombtn">ADD</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CANCEL</button>
                </div>
            </div>
        </div>
    </div>

</body>